version: 0.2

phases:
  pre_build:
    commands:
      - cd shelp-client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: shelp-client/build
